- name: Configurar MySQL en la máquina database
  hosts: all
  become: yes

  vars:
    contrasenya: "1234"
    db_name: "hospital"
    sql_schema_file: "/tmp/hospital_schema.sql"

  tasks:
    - name: Instalar MySQL Server y Cliente
      apt:
        name: 
          - mysql-server
          - mysql-client
        state: present
        update_cache: yes

    - name: Configurar MySQL para aceptar conexiones remotas
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Configurar contraseña de root (para MySQL 5.7+)
      mysql_user:
        name: root
        host_all: true
        password: "{{ contrasenya }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true

    - name: Crear base de datos hospital
      mysql_db:
        name: "{{ db_name }}"
        state: present
        encoding: utf8
        collation: utf8_spanish_ci
        login_user: root
        login_password: "{{ contrasenya }}"

    - name: Subir esquema SQL al servidor
      copy:
        dest: "{{ sql_schema_file }}"
        content: |
          USE hospital;

          CREATE TABLE IF NOT EXISTS persona (
            id_persona INT AUTO_INCREMENT PRIMARY KEY,
            DNI VARCHAR(20) UNIQUE,
            nombre VARCHAR(50),
            apellido1 VARCHAR(50),
            apellido2 VARCHAR(50),
            fecha_nacimiento DATE,
            direccion VARCHAR(100),
            contacto VARCHAR(50)
          );

          CREATE TABLE IF NOT EXISTS usuario (
            id_persona INT,
            login VARCHAR(100) UNIQUE,
            contrasenya VARCHAR(20),
            categoria VARCHAR(8),
            FOREIGN KEY (id_persona) REFERENCES persona(id_persona) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS paciente (
            id_persona INT,
            NSS VARCHAR(20),
            doctor INT,
            estado_ingresado BOOLEAN,
            ubicacion VARCHAR(100),
            familiares TEXT,
            FOREIGN KEY (id_persona) REFERENCES persona(id_persona) ON DELETE CASCADE,
            FOREIGN KEY (doctor) REFERENCES persona(id_persona)
          );

          CREATE TABLE IF NOT EXISTS doctor (
            id_persona INT,
            especialidad VARCHAR(100),
            FOREIGN KEY (id_persona) REFERENCES persona(id_persona) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS historial (
            id_paciente INT PRIMARY KEY,
            grupo_sanguineo VARCHAR(3),
            alergias TEXT,
            FOREIGN KEY (id_paciente) REFERENCES persona(id_persona) ON DELETE CASCADE
          );

          CREATE TABLE IF NOT EXISTS ficha_medica (
            id_ficha INT AUTO_INCREMENT PRIMARY KEY,
            id_paciente INT,
            doctor INT,
            fecha DATE,
            diagnostico VARCHAR(50),
            tratamiento VARCHAR(50),
            observaciones TEXT,
            FOREIGN KEY (id_paciente) REFERENCES historial(id_paciente),
            FOREIGN KEY (doctor) REFERENCES persona(id_persona)
          );

          CREATE TABLE IF NOT EXISTS cita (
            id_cita INT AUTO_INCREMENT PRIMARY KEY,
            paciente INT,
            doctor INT,
            fecha DATETIME,
            motivo VARCHAR(50),
            observaciones TEXT,
            FOREIGN KEY (paciente) REFERENCES persona(id_persona),
            FOREIGN KEY (doctor) REFERENCES persona(id_persona)
          );

          CREATE TABLE IF NOT EXISTS beeper (
            id INT AUTO_INCREMENT PRIMARY KEY,
            receptor VARCHAR(3),
            mensaje TEXT,
            FOREIGN KEY (receptor) REFERENCES persona(id_persona)
          );

          CREATE TABLE IF NOT EXISTS parking (
            id INT AUTO_INCREMENT PRIMARY KEY,
            plaza INT,
            ocupada BOOLEAN,
            matricula_coche VARCHAR(20)
          );

    - name: Ejecutar esquema SQL en la base de datos
      mysql_db:
        name: "{{ db_name }}"
        state: import
        target: "{{ sql_schema_file }}"
        login_user: root
        login_password: "{{ contrasenya }}"

