- name: Configurar MySQL en la máquina database
  hosts: database
  become: yes
  tasks:
    - name: Instalar MySQL Server y Cliente
      apt:
        name: 
          - mysql-server
          - mysql-client
          - git
        state: present
        update_cache: yes

    - name: Configurar MySQL para aceptar conexiones remotas
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present

    - name: Quitar la lentitud para conexiones remotas
      become: true
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        insertafter: '^\[mysqld\]'
        line: skip-name-resolve

    - name: Crear directorio /hospital
      file:
        path: /hospital
        state: directory
        mode: '0755'
        
    - name: Descargar hospital.sql desde GitHub
      get_url:
        url: https://raw.githubusercontent.com/Braidoh/hospital/main/hospital.sql
        dest: /hospital/hospital.sql

    - name: Descargar inserts.sql desde GitHub
      get_url:
        url: https://raw.githubusercontent.com/Braidoh/hospital/main/inserts.sql
        dest: /hospital/inserts.sql

    - name: Crear base de datos con hospital.sql
      mysql_db:
        name: hospital
        state: import
        target: /hospital/hospital.sql
        login_user: root
        login_password: "1234"

    - name: Poner datos con inserts.sql
      mysql_db:
        name: hospital
        state: import
        target: /hospital/inserts.sql
        login_user: root
        login_password: "1234"

    - name: Crear usuario de base de datos
      mysql_user:
        name: root
        password: "1234"
        priv: 'hospital.*:ALL'
        host: '10.0.1.3'
        state: present
        login_user: root
        login_password: "1234"

    - name: Reiniciar MySQL
      systemd:
        name: mysql
        state: restarted
