- name: DNS
  hosts: dns
  become: yes
  tasks:
    - name: Instalar bind9
      apt:
        name: bind9
        state: present
        update_cache: yes

    - name: Configurar named.conf.local
      copy:
        dest: /etc/bind/named.conf.local
        content: |
          zone "servicio.local" {
            type master;
            file "db.servicio.local";
          };

          zone "hospital.local" {
            type master;
            file "db.hospital.local";
          };

          zone "mail.local" {
            type master;
            file "db.mail.local";
          };
          
          zone "concesionario.local" {
            type master;
            file "db.concesionario.local";
          };

          zone "escuela.local" {
            type master;
            file "db.escuela.local";
          };

    - name: Crear archivo de la zona servicio
      copy:
        dest: /var/cache/bind/db.servicio.local
        owner: root
        group: bind
        mode: '0644'
        content: |
          $TTL 604800
          @  IN  SOA  ada.servicio.local. root.servicio.local. (
                 2          ; Serial
                 604800     ; Refresh
                 86400      ; Retry
                 2419200    ; Expire
                 604800 )   ; Negative Cache TTL
          ;
          @      IN  NS  ada.servicio.local.
          ada    IN  A   10.0.1.2

    - name: Crear archivo de la zona hospital
      copy:
        dest: /var/cache/bind/db.hospital.local
        owner: root
        group: bind
        mode: '0644'
        content: |
          $TTL 604800
          @  IN  SOA  zona.hospital.local. root.hospital.local. (
                 2          ; Serial
                 604800     ; Refresh
                 86400      ; Retry
                 2419200    ; Expire
                 604800 )   ; Negative Cache TTL
          ;
          @      IN  NS  zona.hospital.local.
          zona    IN  A   10.0.1.3
          www    IN  A  zona

          inicio  IN  A   10.0.1.10
          login   IN  A   10.0.1.10
          session IN  A   10.0.1.10
          logout  IN  A   10.0.1.10
          admin  IN  A   10.0.1.10
          doctor  IN  A   10.0.1.10
          paciente  IN  A   10.0.1.10
          visitante  IN  A   10.0.1.10
          save  IN  A   10.0.1.10
          cita  IN  A   10.0.1.10


    - name: Crear archivo de la zona mail
      copy:
        dest: /var/cache/bind/db.mail.local
        owner: root
        group: bind
        mode: '0644'
        content: |
          $TTL 604800
          @  IN  SOA  ada.mail.local. root.mail.local. (
            2          ; Serial
            604800     ; Refresh
            86400      ; Retry
            2419200    ; Expire
            604800 )   ; Negative Cache TTL
          ;
          @      IN  NS  ada.mail.local.
          ada  IN  A   10.0.1.4

    - name: Crear archivo de zona directa para concesionario
      copy:
        dest: /var/cache/bind/db.concesionario.local
        owner: root
        group: bind
        mode: '0644'
        content: |
          $TTL 604800
          @  IN  SOA  coche.concesionario.local. root.concesionario.local. (
                 2          ; Serial
                 604800     ; Refresh
                 86400      ; Retry
                 2419200    ; Expire
                 604800 )   ; Negative Cache TTL
          ;
          @      IN  NS  coche.concesionario.local.
          coche    IN  A   10.0.2.6

    - name: Crear archivo de la zona escuela
      copy:
        dest: /var/cache/bind/db.escuela.local
        owner: root
        group: bind
        mode: '0644'
        content: |
          $TTL 604800
          @  IN  SOA  campus.escuela.local. root.escuela.local. (
            2          ; Serial
            604800     ; Refresh
            86400      ; Retry
            2419200    ; Expire
            604800 )   ; Negative Cache TTL
          ;
          @      IN  NS  campus.escuela.local.
          campus  IN  A   10.0.2.7

    - name: Habilitar forwarders
      copy:
        dest: /etc/bind/named.conf.options
        owner: root
        group: bind
        mode: '0644'
        content: |
          options {
          directory "/var/cache/bind";
            forwarders {
              8.8.8.8;
            };
            dnssec-validation auto;
            listen-on-v6 { any; };
          };

    - name: Habilitar y reiniciar el servicio BIND9
      systemd:
        name: bind9
        enabled: yes
        state: restarted   