- name: Desplegar Pagina Web Hospital
  hosts: webserver
  become: yes
  vars:
    repo_url: "https://github.com/Braidoh/hospital.git"
    db_ip: "10.0.2.3"
    document_root: "/var/www/"
    domain : "10.0.1.3 www.hospital.local"

  tasks:
    - name: Instalar Apache y módulos necesarios
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - git
          - openssl
          - mysql-client
        state: present
        update_cache: yes

    - name: Asegurar que el módulo SSL esté habilitado
      apache2_module:
        name: ssl
        state: present

    - name: Clonar el repositorio del hospital
      command: git clone {{ repo_url }} {{ document_root }}

#    - name: Eliminar archivos no .php
#      command: remove hospital.sql inserts.sql

    - name: Añadir hospital en apache2.conf
      blockinfile:
        path: /etc/apache2/apache2.conf
        block: |
          <Directory /var/www/hospital>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
          </Directory>

    - name: Archivo de configuración sites-available
      blockinfile:
        path: /etc/apache2/sites-available/hospital.conf
        block: |
          <VirtualHost *:80>
            ServerName www.hospital.local
            ServerAlias *.hospital.local
            Redirect permanent / https://%{HTTP_HOST}/
          </VirtualHost>

          <VirtualHost *:443>
            ServerName hospital.local
            ServerAlias *.hospital.local
            DocumentRoot /var/www/hospital

            SSLEngine on
            SSLCertificateFile /etc/ssl/certs/hospital.crt
            SSLCertificateKeyFile /etc/ssl/private/hospital.key

            DirectoryIndex inicio.php

            ErrorLog ${APACHE_LOG_DIR}/hospital_error.log
            CustomLog ${APACHE_LOG_DIR}/hospital_access.log combined
          </VirtualHost>
      
    - name: Archivo de configuración sites-enabled
      copy:
        src: /etc/apache2/sites-available/hospital.conf
        dest: /etc/apache2/sites-enabled/hospital.conf
        remote_src: yes

    - name: Crear certificado autofirmado 
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/hospital.key -out /etc/ssl/certs/hospital.crt -subj "/C=ES/ST=Barcelona/L=Barcelona/O=Hospital/CN=*.hospital.local"

    - name: Habilitar los módulos necesarios
      command: a2enmod rewrite

    - name: Habilitar los módulos necesarios
      command: a2enmod ssl
    
    - name: Deshabilitar el sitio predeterminado
      command: a2dissite 000-default.conf

    - name: Habilitar cada sitio
      command: a2ensite hospital.conf    

    - name: Agregar entradas a /etc/hosts (evita dependencias de DNS)
      lineinfile:
        path: /etc/hosts
        line: "{{ domain }}"
        create: yes

    - name: Definir ServerName global para evitar advertencia
      lineinfile:
        path: /etc/apache2/apache2.conf
        line: "ServerName hospital.local"
        create: yes

    - name: Reiniciar Apache y habilitar servicio
      systemd:
        name: apache2
        enabled: yes
        state: restarted