- name: Desplegar Pagina Web Hospital
  hosts: webserver
  become: yes
  vars:
    repo_url: "https://github.com/Braidoh/hospital.git"
    db_ip: "10.0.2.3"
    document_root: "/var/www/hospital"
    fichero_hosts: "127.0.0.1 admin.local doctor.local paciente.local visitante.local inicio.local login.local session.local logout.local save.local cita.local"
    sitios:
      - inicio
      - login
      - session
      - logout
      - admin
      - doctor
      - paciente
      - visitante
      - save.      
      - cita

  tasks:
    - name: Asegurar que el módulo SSL esté habilitado
      apache2_module:
        name: ssl
        state: present

    - name: Clonar el repositorio
      git:
        repo: "{{ repo_url }}"
        dest: "{{ document_root }}"
        update: yes

    #- name: Eliminar archivos no .php
    #  shell: find "{{ document_root }}" -type f ! \( -name "*.php" -o -name "*.jpg" \) -delete

    # Codigo aquí

    # Crear archivo de configuración para cada sitio (sites-available y sites-enabled)
    - name: Archivo de configuración sites-available
      copy:
        dest: /etc/apache2/sites-available/{{ item }}.conf
        content: |
          <VirtualHost *:443>
              ServerName {{ item }}.local
              DocumentRoot {{ document_root }}
              <Directory {{ document_root }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              DirectoryIndex {{ item }}.php
          </VirtualHost>
      loop: "{{ sitios }}"

    - name: Archivo de configuración sites-enabled    
      copy:
        dest: /etc/apache2/sites-enabled/{{ item }}.conf
        content: |
          <VirtualHost *:443>
              ServerName {{ item }}.local
              DocumentRoot {{ document_root }}
              <Directory {{ document_root }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
              DirectoryIndex {{ item }}.php
          </VirtualHost>
      loop: "{{ sitios }}"
    
    - name: Deshabilitar el sitio predeterminado
      command: a2dissite 000-default.conf

    - name: Habilitar cada sitio
      command: a2ensite {{ item }}.conf
      loop: "{{ sitios }}"

    - name: Agregar entradas a /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ fichero_hosts }}"
        create: yes    

    - name: Reiniciar Apache y habilitar servicio
      systemd:
        name: apache2
        enabled: yes
        state: restarted